# fly.toml app configuration file generated for crypto-explorer-backend on 2025-03-28T20:47:54+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'crypto-explorer-backend'
primary_region = 'arn'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
